#!/bin/sh

FW32_ROOT="/usr/lib/fw32"
FW32_CONFIG="/etc/fw32/pacman-g2.conf"
FW32_DIRS=(
	'/proc'
	'/sys'
	'/dev'
	'/etc'
	'/home'
	'/tmp'
	'/var/tmp'
	'/var/cache/pacman-g2/pkg'
	'/usr/share/kde'
	'/usr/share/icons'
	'/usr/share/fonts'
	'/usr/share/themes'
)

error()
{
	/usr/bin/echo "$1"
	exit 1
}

mount()
{
	/usr/bin/grep -q "$FW32_ROOT/$1" /proc/mounts
	[ $? -eq 0 ] && return
	/bin/mount --bind "$1" "$FW32_ROOT/$1"
	[ $? -ne 0 ] && error "Failed to mount $1."
}

umount()
{
	/bin/umount "$FW32_ROOT/$1"
	[ $? -ne 0 ] && error "Failed to umount $1."
}

mkdir()
{
	/usr/bin/mkdir -p "$FW32_ROOT/$1"
	[ $? -ne 0 ] && "Failed to create directory $1."
}

pacman_g2()
{
	/usr/bin/linux32 /usr/bin/pacman-g2 --noconfirm --root "$FW32_ROOT" --config "$FW32_CONFIG" $@
	[ $? -ne 0 ] && error "pacman-g2 failed to perform its action."
}

run()
{
	/usr/bin/linux32 /usr/sbin/chroot $FW32_ROOT $@
	[ $? -ne 0 ] && error "Failed to run command $@."
}

mount_all()
{
	for i in ${FW32_DIRS[@]}; do
		mount $i
	done
}

umount_all()
{
	for i in $(/usr/bin/grep -o -E "$FW32_ROOT/[a-zA-Z0-9_/]+" /proc/mounts); do
		umount "$(/usr/bin/echo $i | /usr/bin/sed 's|^$FW32_ROOT||')"
	done
}

create()
{
	[ -d "$FW32_ROOT" ] && error "$FW32_ROOT appears to already exist."
	for i in ${FW32_DIRS[@]}; do
		mkdir $i
	done
	mount /var/cache/pacman-g2/pkg
	pacman_g2 -Sy shadow coreutils findutils which wget file tar gzip bzip2 util-linux procps kbd psmisc less
	umount /var/cache/pacman-g2/pkg
}

update()
{
	umount_all
	mount /var/cache/pacman-g2/pkg
	pacman_g2 -Syuf
	umount /var/cache/pacman-g2/pkg
	mount_all
	run fc-cache --force --system-only
}

delete()
{
	umount_all
	rm -rf $FW32_ROOT
	[ $? -ne 0 ] && error "Failed to delete $FW32_ROOT."
}

[ $UID -ne 0 ] && [ $EUID -ne 0 ] && error "You must run this command as root."
